; Auto-generated Inno Setup script for OfflineAI — DO NOT EDIT by hand.
; Generated by installer.packager from the canonical pyproject version.
; Rebuild with: python -m installer.packager --inno
; Application version: 3.1.0

[Setup]
; Stable AppId: survives version upgrades and binds them to the same
; application entry in Add/Remove Programs.
AppId={{8D4D4AE1-9C2A-4A01-8C40-4B4862A9B3C0}}_OfflineAI
AppName=OfflineAI
AppVersion=3.1.0
; Company/publisher metadata (Add/Remove Programs display only).
AppPublisher=OfflineAI
; Architecture-aware Program Files; the user may change it.
DefaultDirName={autopf}\OfflineAI
; Windows x64-only build (PyInstaller 64-bit payload).
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Normal Windows application installer privileges.  The INSTALLED
; application does not require elevation for its own operation.
PrivilegesRequired=admin
; Least-privilege option (per-user installs) stays available.
PrivilegesRequiredOverridesAllowed=dialog commandline
DefaultGroupName=OfflineAI
DisableProgramGroupPage=yes
UninstallDisplayName=OfflineAI
UninstallDisplayIcon={app}\OfflineAI.exe
OutputDir={#SourcePath}\..\installer_output
OutputBaseFilename=OfflineAI_Setup_3.1.0
Compression=lzma2/max
SolidCompression=yes
; Deterministic builds: no timestamp leak, fixed installer metadata.
TimeStampRounding=0
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Complete Phase 5 onedir payload, packaged recursively: the
; launcher OfflineAI.exe plus the entire _internal tree.
; The launcher entry has no skipif... flag: a missing PyInstaller
; output must abort the compile loudly instead of shipping a
; broken installer.
Source: "{#SourcePath}\..\dist\OfflineAI\OfflineAI.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\..\dist\OfflineAI\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist

[Icons]
Name: "{group}\OfflineAI"; Filename: "{app}\OfflineAI.exe"
Name: "{group}\Uninstall OfflineAI"; Filename: "{uninstallexe}"
Name: "{autodesktop}\OfflineAI"; Filename: "{app}\OfflineAI.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\OfflineAI.exe"; Description: "Launch OfflineAI"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; PHASE 6 uninstall contract: remove ONLY application binaries under
; {app}.  User data (%LOCALAPPDATA%\OfflineAI: projects, knowledge,
; configuration, logs) and the user-selected models root are NEVER
; deleted by the uninstaller.  The recursive {app} cleanup is safe
; because models and user data are architecturally never installed
; under {app}.
Type: filesandordirs; Name: "{app}"

; No model-location UI, no model-path persistence, no user-data
; creation, no telemetry, no extra registry integrations — by design
; (see the PHASE 6 installer architecture).
