"""Installer packaging support for FAZA 12.

Generates PyInstaller spec files and Inno Setup script templates
so the application can be bundled into a Windows installer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

try:
    from PyInstaller.utils.hooks import collect_all
    pyside6_datas, pyside6_binaries, pyside6_hiddenimports = collect_all("PySide6")
    pyside6_datas = list(pyside6_datas) if pyside6_datas else []
    pyside6_binaries = list(pyside6_binaries) if pyside6_binaries else []
    pyside6_hiddenimports = list(pyside6_hiddenimports) if pyside6_hiddenimports else []
except ImportError:
    pyside6_datas = []
    pyside6_binaries = []
    pyside6_hiddenimports = []


@dataclass(frozen=True, slots=True)
class PackageSpec:
    """Metadata for a packaged installer build."""

    app_name: str
    version: str
    entry_point: str
    icon: Path | None = None
    include_pyqt: bool = False
    additional_files: list[tuple[str, str]] = field(default_factory=list)
    target_dir: Path = Path("dist")
    work_dir: Path = Path("build")
    spec_file: Path = field(default_factory=lambda: Path("installer.spec"))


@dataclass(frozen=True, slots=True)
class InnoSetupScript:
    """Generated Inno Setup script content."""

    script_text: str
    output_path: Path


def build_pyinstaller_spec(spec: PackageSpec) -> str:
    """Generate a PyInstaller ``.spec`` file as a string.

    The spec is written to ``spec.spec_file`` and also returned
    as a string so the caller can inspect or write it manually.
    """
    lines = [
        "# -*- mode: python ; coding: utf-8 -*-",
        f"# Auto-generated by installer.packager for {spec.app_name} v{spec.version}",
        "",
        "block_cipher = None",
        "",
        "a = Analysis(",
        f"    ['{spec.entry_point}'],",
        "    pathex=[],",
        "    binaries=[],",
        "    datas=[",
    ]

    for src, dst in spec.additional_files:
        lines.append(f"        ('{src}', '{dst}'),")

    lines.extend([
        "    ],",
        "    hiddenimports=[",
        "        'PySide6',",
        "        'PySide6.QtCore',",
        "        'PySide6.QtGui',",
        "        'PySide6.QtWidgets',",
        "        'shiboken6',",
        "        'core.event_bus',",
        "        'core.router',",
        "        'core.assistant',",
        "        'core.config_manager',",
        "        'core.logger',",
        "        'core.security_layer',",
        "        'plugins',",
        "        'plugins.manager',",
        "        'plugins.models',",
        "        'plugins.base',",
        "        'plugins.discovery',",
        "        'plugins.loader',",
        "        'plugins.registry',",
        "        'tools',",
        "        'tools.base',",
        "        'tools.system_tools',",
        "        'tools.application_tools',",
        "        'tools.file_tools',",
        "        'security.models',",
        "        'security.permission_manager',",
        "        'security.auditor',",
        "        'security.security_layer',",
        "        'voice',",
        "        'voice.manager',",
        "        'voice.stt',",
        "        'voice.tts',",
        "        'voice.wake_word',",
        "        'voice.base',",
        "        'ai.engine.llm_engine',",
        "        'ai.engine.inference',",
        "        'ai.models.model_manager',",
        "        'ai.models.model_loader',",
        "        'ai.prompts.system_prompts',",
        "        'ai.prompts.templates',",
        "        'memory.memory_manager',",
        "        'memory.short_term',",
        "        'memory.long_term',",
        "        'memory.vector_memory',",
        "        'memory.embeddings',",
        "        'tools.system_tools',",
        "        'automation.manager',",
        "        'automation.scheduler',",
        "        'automation.workflow',",
        "        'automation.task',",
        "        'agent.orchestrator',",
        "        'agent.planner',",
        "        'agent.reasoning',",
        "        'agent.base',",
        "        'agent.task',",
        "    ],",
        "    hookspath=[],",
        "    hooksconfig={},",
        "    runtime_hooks=[],",
        "    excludes=[",
        "        'tkinter',",
        "        'unittest',",
        "        'test',",
        "        'tests',",
        "        'docs',",
        "        'installer',",
        "    ],",
        "    win_no_prefer_redirects=False,",
        "    win_private_assemblies=False,",
        "    cipher=block_cipher,",
        "    noarchive=False,",
        ")",
        "",
        "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)",
        "",
        "exe = EXE(",
        "    pyz,",
        "    a.scripts,",
        "    a.binaries,",
        "    a.zipfiles,",
        "    a.datas,",
        "    [],",
        f"    name='{spec.app_name}',",
        "    debug=False,",
        "    bootloader_ignore_signals=False,",
        "    strip=False,",
        "    upx=True,",
        "    upx_exclude=[],",
        "    runtime_tmpdir=None,",
        "    console=True,",
        "    disable_windowed_traceback=False,",
        "    argv_emulation=False,",
        "    target_arch=None,",
        "    codesign_identity=None,",
        "    entitlements_file=None,",
        "    icon=None,",
        ")",
        "",
        "coll = COLLECT(",
        "    exe,",
        "    a.binaries,",
        "    a.zipfiles,",
        "    a.datas,",
        "    strip=False,",
        "    upx=True,",
        "    upx_exclude=[],",
        f"    name='{spec.app_name}',",
        ")",
    ])

    return "\n".join(lines)


def write_pyinstaller_spec(spec: PackageSpec, path: Path | None = None) -> Path:
    """Write the generated spec file to disk.

    Defaults to ``spec.spec_file`` if ``path`` is not provided.
    """
    out = path or spec.spec_file
    out.parent.mkdir(parents=True, exist_ok=True)
    content = build_pyinstaller_spec(spec)
    out.write_text(content, encoding="utf-8")
    return out


def build_inno_setup_script(
    app_name: str,
    version: str,
    app_filename: str,
    install_dir: str = r"C:\Program Files\OfflineAI",
    output_path: Path | None = None,
) -> InnoSetupScript:
    """Generate an Inno Setup ``.iss`` script as a string.

    The script installs the PyInstaller-bundled application, creates
    a Start Menu shortcut, and registers the application in the
    Windows uninstall registry.
    """
    safe_name = app_name.replace(" ", "")
    user_data_dir = r"{localappdata}\OfflineAI"
    lines = [
        "; Auto-generated Inno Setup script for Offline AI Assistant",
        f"; Version {version}",
        "",
        "[Setup]",
        f"AppName={app_name}",
        f"AppVersion={version}",
        f"DefaultDirName={install_dir}",
        "DefaultGroupName=Offline AI Assistant",
        "OutputDir=installer_output",
        f"OutputBaseFilename={safe_name}_Setup_{version}",
        "Compression=lzma",
        "SolidCompression=yes",
        "PrivilegesRequired=admin",
        "",
        "[Languages]",
        "Name: english; MessagesFile: compiler:Default.isl",
        "",
        "[Tasks]",
        'Name: desktopicon; Description: Create a &desktop icon; GroupDescription: Additional icons:',
        "",
        "[Files]",
        f'Source: "dist\\{safe_name}\\{safe_name}.exe"; DestDir: "{{app}}"; Flags: ignoreversion',
        "",
        "[Dirs]",
        f'DirName: "{user_data_dir}\\config"',
        f'DirName: "{user_data_dir}\\data"',
        f'DirName: "{user_data_dir}\\logs"',
        "",
        "[Icons]",
        f'Name: "{{group}}\\{app_name}"; Filename: "{{app}}\\{safe_name}.exe"',
        'Name: "{group}\\{#emit AppName} (Uninstall)"; Filename: "{uninstallexe}"',
        f'Name: "{{commondesktop}}\\{app_name}"; Filename: "{{app}}\\{safe_name}.exe"; Tasks: desktopicon',
        "",
        "[Run]",
        f'Filename: "{{app}}\\{safe_name}.exe"; Description: "Launch Offline AI Assistant"; Flags: nowait postinstall skipifsilent',
        "",
        "[UninstallDelete]",
        f'Type: filesandordirs; Name: "{{app}}\\{safe_name}.exe"',
    ]

    script_text = "\n".join(lines)
    out = output_path or Path(f"{safe_name}.iss")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script_text, encoding="utf-8")
    return InnoSetupScript(script_text=script_text, output_path=out)


def generate_installer_package(
    spec: PackageSpec,
    inno_output: Path | None = None,
) -> tuple[str, InnoSetupScript]:
    """Generate both the PyInstaller spec and Inno Setup script.

    Returns the spec content string and the InnoSetupScript object.
    """
    spec_content = build_pyinstaller_spec(spec)
    write_pyinstaller_spec(spec)

    iss = build_inno_setup_script(
        app_name=spec.app_name,
        version=spec.version,
        app_filename=spec.app_name.replace(" ", ""),
        output_path=inno_output,
    )

    return spec_content, iss
